// Code generated by protoc-gen-go. DO NOT EDIT.
// source: person.proto

/*
Package model is a generated protocol buffer package.

It is generated from these files:
	person.proto

It has these top-level messages:
	Person
*/
package model

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Person struct {
	FirstName string           `protobuf:"bytes,1,opt,name=first_name,json=firstName" json:"first_name,omitempty"`
	LastName  string           `protobuf:"bytes,2,opt,name=last_name,json=lastName" json:"last_name,omitempty"`
	Age       int32            `protobuf:"varint,3,opt,name=age" json:"age,omitempty"`
	Parents   []*Person_Parent `protobuf:"bytes,4,rep,name=parents" json:"parents,omitempty"`
}

func (m *Person) Reset()                    { *m = Person{} }
func (m *Person) String() string            { return proto.CompactTextString(m) }
func (*Person) ProtoMessage()               {}
func (*Person) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Person) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *Person) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *Person) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *Person) GetParents() []*Person_Parent {
	if m != nil {
		return m.Parents
	}
	return nil
}

type Person_Parent struct {
	FirstName string `protobuf:"bytes,1,opt,name=first_name,json=firstName" json:"first_name,omitempty"`
	LastName  string `protobuf:"bytes,2,opt,name=last_name,json=lastName" json:"last_name,omitempty"`
}

func (m *Person_Parent) Reset()                    { *m = Person_Parent{} }
func (m *Person_Parent) String() string            { return proto.CompactTextString(m) }
func (*Person_Parent) ProtoMessage()               {}
func (*Person_Parent) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

func (m *Person_Parent) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *Person_Parent) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func init() {
	proto.RegisterType((*Person)(nil), "model.Person")
	proto.RegisterType((*Person_Parent)(nil), "model.Person.Parent")
}

func init() { proto.RegisterFile("person.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 157 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x29, 0x48, 0x2d, 0x2a,
	0xce, 0xcf, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xcd, 0xcd, 0x4f, 0x49, 0xcd, 0x51,
	0x3a, 0xc3, 0xc8, 0xc5, 0x16, 0x00, 0x16, 0x17, 0x92, 0xe5, 0xe2, 0x4a, 0xcb, 0x2c, 0x2a, 0x2e,
	0x89, 0xcf, 0x4b, 0xcc, 0x4d, 0x95, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0xe2, 0x04, 0x8b, 0xf8,
	0x25, 0xe6, 0xa6, 0x0a, 0x49, 0x73, 0x71, 0xe6, 0x24, 0xc2, 0x64, 0x99, 0xc0, 0xb2, 0x1c, 0x20,
	0x01, 0xb0, 0xa4, 0x00, 0x17, 0x73, 0x62, 0x7a, 0xaa, 0x04, 0xb3, 0x02, 0xa3, 0x06, 0x6b, 0x10,
	0x88, 0x29, 0xa4, 0xc7, 0xc5, 0x5e, 0x90, 0x58, 0x94, 0x9a, 0x57, 0x52, 0x2c, 0xc1, 0xa2, 0xc0,
	0xac, 0xc1, 0x6d, 0x24, 0xa2, 0x07, 0xb6, 0x51, 0x0f, 0x62, 0x9b, 0x5e, 0x00, 0x58, 0x32, 0x08,
	0xa6, 0x48, 0xca, 0x85, 0x8b, 0x0d, 0x22, 0x44, 0x89, 0x3b, 0x92, 0xd8, 0xc0, 0x9e, 0x33, 0x06,
	0x04, 0x00, 0x00, 0xff, 0xff, 0x54, 0xc4, 0x51, 0x62, 0xec, 0x00, 0x00, 0x00,
}
